/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prasoon_panoramastitching_NativePanorama */

#ifndef _Included_com_prasoon_panoramastitching_NativePanorama
#define _Included_com_prasoon_panoramastitching_NativePanorama
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_prasoon_panoramastitching_NativePanorama
 * Method:    processPanorama
 * Signature: ([JJ)I
 */
JNIEXPORT jint JNICALL Java_com_prasoon_panoramastitching_NativePanorama_processPanorama
  (JNIEnv *, jclass, jlongArray, jlong);

/*
 * Class:     com_prasoon_panoramastitching_NativePanorama
 * Method:    getMessageFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_prasoon_panoramastitching_NativePanorama_getMessageFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
